version: '3'

vars:
  MIGRATIONS_DIR: ./cmd/migrations
  POSTGRES_URI: "postgres://postgres:mysecretpassword@localhost:5432/online_football_tycoon?sslmode=disable"

tasks:
  migration-create:
    desc: "Create a new migration file"
    cmds:
      - docker run --rm -v {{.MIGRATIONS_DIR | fromSlash | abs | toSlash}}:/migrations/ migrate/migrate create -ext sql {{.CLI_ARGS}}

  migration-up:
    desc: "Run migrations UP"
    cmds:
      - go run cmd/main.go migrations

  migration-down:
    desc: "Run migrations DOWN (all)"
    cmds:
      - docker run --rm -v {{.MIGRATIONS_DIR | fromSlash | abs | toSlash}}:/migrations/ --network host migrate/migrate -database "{{.POSTGRES_URI}}" -source "file:///migrations" down --all {{.CLI_ARGS}}

